spec:
  template:
    spec:
      containers:
        - 
          resources:
            requests:
              cpu: "1.0"
              memory: 512Mi
            limits:
              cpu: "1.0"
              memory: 1Gi